Update predict pipeline
stanford-oval/genie-k8s pull request #47
Opened 2021-03-12 05:22 UTC by Mehrad0711

Add option to do prediction on pretrained models.
Relate PR in genienlp: https://github.com/stanford-oval/genienlp/pull/107

2021-03-12 06:21 UTC, s-jse commented
Why do we need the `prediction-small` pipeline? The cost of having 4 GPUs in parallel is almost the same as having one GPU machine for longer.
Also, the number of GPUs can be an input parameter, like what we have for training pipelines.

2021-03-12 07:13 UTC, Mehrad0711 commented
Yeah but I noticed for predictions on small datasets, the actual generation time is small so it would be cheaper to use g4dn.4xlarge. In fact, 2xlarge or even xlarge should be sufficient but we don't have them in our nodegroup yet.

2021-03-15 04:27 UTC, gcampax reviewed
I'm not sure i understand this PR, it creates new small pipelines, but the small pipelines are still g4dn.4xlarge?

2021-03-15 05:06 UTC, s-jse commented
> 
> 
> I'm not sure i understand this PR, it creates new small pipelines, but the small pipelines are still g4dn.4xlarge?

It has one GPU instead of 4.

2021-03-15 05:09 UTC, s-jse requested changes
Instead of a new pipeline, number of GPUs can be an input parameter. Similar to training pipelines (https://github.com/stanford-oval/genie-k8s/blob/master/pipelines/training.py#L107), but instead of a constant in the code, surfaced to the kubeflow experiment UI as well.

2021-03-15 05:20 UTC, Mehrad0711 commented
num_gpus is a runtime parameter, it won't be available at compile-time. Additionally, the node selector decides number of gpus so I can't reuse `predict` pipeline that uses `g4dn.12xlarge` with only 1 gpu.

2021-03-15 05:36 UTC, s-jse approved these changes
Please add the new pipelines to `upload_all_pipelines.sh` as well.

2021-03-15 05:36 UTC, s-jse commented on pipelines/training.py
> +    name='Predict',
Use a unique name for pipelines.

2021-03-15 06:02 UTC, Mehrad0711 commented
> Please add the new pipelines to `upload_all_pipelines.sh` as well.

I'm sending a followup PR which has some updates including this (I needed to add bootleg pipeline too).

2021-03-15 06:04 UTC, Mehrad0711 commented
Will update predict pipelines with this merge though.

2021-03-15 06:04 UTC, merged